name: MacOS
 
on:
    push:
        branches: '*'
    pull_request:
        branches: '*'
 
jobs:
  perl-job:
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Perl
        run: brew install perl
      - name: Ensure we have a working toolchain
        run: cpanm --notest ExtUtils::Manifest App::cpanminus Dist::Zilla
      - name: Run tests
        run: |
          dzil authordeps --missing | cpanm --notest
          dzil listdeps --author --missing | cpanm --notest
          dzil test --author --release
