name: Windows
 
on:
    push:
        branches: '*'
    pull_request:
        branches: '*'
 
jobs:
  perl-job:
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        perl-version:
          - '5.20'
          # - '5.22'
          # - '5.24'
          # - '5.26'
          # - '5.28'
          # - '5.30'
          # - '5.32'
          # - '5.34'
          # - '5.36'
          # - 'latest'
    name: Perl ${{ matrix.perl-version }}
    steps:
      - name: Setup perl
        uses: shogo82148/actions-setup-perl@v1
        with:
          perl-version: ${{ matrix.perl-version }}
          distribution: strawberry
      - name: Set git to use LF
        run: |
          git config --global core.autocrlf false
          git config --global core.eol lf
      - uses: actions/checkout@v2
      - name: Ensure we have a working toolchain
        run: cpanm --notest ExtUtils::Manifest App::cpanminus Dist::Zilla
      # - name: Install dependencies
      #   run: cpanm --notest --installdeps .
      - name: Run tests
        run: |
          dzil authordeps --missing | cpanm --notest
          dzil listdeps --author --missing | cpanm --notest
          dzil test --author --release
